### ISSUE TITLE
Remove the polyfills for unsupported browsers (previously: Remove core-js and regenerator-runtime dependencies)

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1011]
### Description

Remove unused dependencies:
-  `core-js`
- `regenerator-runtime`

### Links

- https://handsoncode.slack.com/archives/C031GBX62SE/p1654729678790179 (internal discussion)
- #1006 
- #896

**Comment by warpech** [comment]
In this issue we will be changing the Webpack config. While at it, please also remove unused workaround for GPU: https://github.com/handsontable/hyperformula/blob/3e412092ff5ddafeeec77605c1d44c7559e7f785/.config/webpack/production.js#L23-L24

Maybe it will improve the bundle size (#1006).

**Comment by warpech** [comment]
My assumptions for this issue:
- Core-js will be removed as a dependency, because we no longer need polyfills
- Regenerator-runtime will be removed as a dependency. We don't use async/await, so I am not sure if it is even needed currently
- The [supported browsers](https://handsontable.com/docs/supported-browsers/) and Node 14+ will continue to work

I think we need to make sure that all builds are verified in the supported envs:
- ES Module - (1) in browser, through a bundler; (2) in Node; (3) directly in a browser (only if that's possible now)
- CommonJS - (1) in browser, through a bundler; (2) in Node
- UMD (`dist`) - (1) directly in a browser

**Comment by AMBudnik** [comment]
Closed as released in version [2.1.0](https://github.com/handsontable/hyperformula/releases/tag/2.1.0).
