### ISSUE TITLE
HyperFormula.languages returns only `enGB`.

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1022]
### Description

[Reference about HyperFormula.languages property](https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#languages) says:
> Contains all available languages to use in registerLanguage.

Also, [Localizing functions guide](https://handsontable.github.io/hyperformula/guide/localizing-functions.html) mentions this property as a way to get all the available languages.

### Steps to reproduce

1. Call `HyperFormula.languages`

**Expected result**: Get 16 supported languages.
**Actual result**: Get only one language, `enGB`.

**Comment by wojciechczerniak** [comment]
> Expected result: Get 16 supported languages.

Nope. Languages available for `registerLanguage` are those that are loaded on the page. If you don't attach additional files, they are not available. If someone loads his own languages then can even have 32 supported languages there.

Check any UMD language file:
```js
if (!_.default.languages) {
  _.default.languages = {};
}

_.default.languages[dictionary.langCode] = dictionary;
var _default = dictionary;
exports.default = _default;
```
It's just an object that creates a namespace for languages so when loaded they will not pollute global scope. Documentation you're referring to mentions `Hypefromula.languages` only in UMD context. For ES modules property is not populated because modules are isolated (can't be done and it doesn't make sense anyway).

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/hyperformula/pull/1348/files in HyperFormula 2.6.1
