### ISSUE TITLE
DAY function returns incorrect result if date is empty

### ISSUE THREAD

**Issue by dksingla** [handsontable/hyperformula#1084]
### Description

DAY function uses a Date column as a parameter if a cell in the Date column is empty, the DAY function returns 30 instead of an empty value.

### Steps to reproduce
Please refer a the sandbox https://codesandbox.io/s/solitary-silence-wlne90?file=/src/data.js

### Demo
https://codesandbox.io/s/solitary-silence-wlne90?file=/src/data.js

* HyperFormula version: 2.1
* Browser Name and version: ANY
* Operating System: ANY

**Comment by sequba** [comment]
Hi, @dksingla thanks for your report.

We see a number of mechanisms here:
- in HyperFromula dates are stored as numbers, so what the `DAY()` function expects is in fact a number
- an empty value, when cast to a number, results in 0
- number 0 represents date `30/12/1899` ([nullDate](https://hyperformula.handsontable.com/api/interfaces/configparams.html#nulldate))

But this result is indeed unexpected. We need to investigate what the [ODF standard](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) says about it and how other spreadsheets behave.

**Comment by sequba** [comment]
@dksingla As a workaround for this issue you might use the `IF()` function:
```
=IF(A2, DAY(A2), "")
```

**Comment by sequba** [comment]
@dksingla, I analyzed this issue.

ODFF specifies that:
- [DAY function expects a DateParam argument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html#__RefHeading__1018180_715980110)
- [An empty cell results in value `0`, when automatically converted to DateParam](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html#__RefHeading__1018006_715980110)
- [Suggest that the number `0` should represent date `1899-12-30` for evaluators that don't replicate the leap year bug (such as HF)](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html#__RefHeading__1017888_715980110)

These are the results for formula `=DAY(A2)` where A2 is empty in popular spreadsheet software:

| Microsoft Excel | Google Sheets | HyperFormula | HyperFormula in [Excel compatibility mode](https://hyperformula.handsontable.com/guide/compatibility-with-microsoft-excel.html#leap-year-bug) |
|---|---|---|---|
| 0 | 30 | 30 | 31 |

In my opinion, `0` is not a logical result because it is not a valid day number for any date. Also, it is not compliment with ODFF standard. I would keep the current behavior of HyperFormula.

CC: @adamu-handsontable

**Comment by sequba** [comment]
Closing
