### ISSUE TITLE
Run license key validation on first read operation

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1181]
### Description

To make integration with Handsontable easier, we don't want to display the `license key missing` warning when HyperFormula instance is created but only when user reads data from it.

Functions that should trigger license key validation:
- getCellValue
- getSheetValues
- getAllSheetsValues
- copy
- cut
- getRangeValues
- getNamedExpressionValue
- calculateFormula

Functions that must not trigger license key validation:
- buildFrom* methods
- updateConfig
- addNamedExpression
- addSheet
- setCellContents

## Links

https://github.com/handsontable/dev-handsontable/issues/587

**Comment by sequba** [comment]
The estimate is `0` as the effort is tracked in the corresponding HOT issue.

**Comment by adamu-handsontable** [comment]
It was decided that, approach taken in task definition was not the correct one. It is actually a workaround for the real problem. The actual problem is that it is impossible to pass HF configuration in HOT directly instead of passing already initialised HF instance. We will have another go at this problem in the future.
