### ISSUE TITLE
Function meta data format

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#2]
### Description

Function meta can be used to provide syntax highlight, editor help, contextual help or generate documentation pages similar to those attached at the bottom of this issue.

We don't have to use all the fields that are described here. But should be ready to extend the schema if we need to do it in the future.

Inspiration source: 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json

Interesting fact:
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration
JSON metadata might be generated from JSDoc. For the English language only, I guess.

Google Spreadsheet has a very similar JSDoc format for custom functions:
https://developers.google.com/apps-script/guides/sheets/functions

### Example
```ts
{
  id: "SUM",
  name: "SUM",
  description: "Short description for editor and category list.",
  notes: "Longer article about formula and it's use cases. Might include Markdown for rich editing",
  helpUrl: "https://hyperformula.com/formulas/en/sum", // can be generated?
  categories: ["Financial"],
  examples: [
    "=SUM(A1:A4, 101)",
  ],
  parameters: [
    {
      name: "Parameter name",
      descriptions: "Parameter short description",
      optional: false,
      repeating: true,
    }
  ],
  since: "1.2.0",
  see: ["SUMIF"],
  options: {
    useGPU: false,
    volatile: false,
  }
}
```

#### Function
| Property         | Data type | Required | Description     |                                                                                                                                           
|---------------|-----------|----------|----------------|
| `description` | string        | No           |                         |
| `helpUrl`        | string       | No           | URL that provides information about the function.    |
| `id`                 | string       | Yes          | A unique ID for the function.     |
| `name`           | string       | Yes          | The name of the function that end-users see. |
| `options`        | object      | No           | See options for details.   |
| `parameters` | array        | Yes          | Array that defines the input parameters for the function.  |
| `examples`     | array       | No       |    |
| `notes`           | string      | No      |  field to describe quirks and use cases  |
| `see`              | array        | No      |  for the references to similar formulas  |
| `categories`   | array        | No      |  to group formulas  |
| `since`           | string       | No      |  in which the formula was introduced  |

#### Options:

| Property     | Data type | Required | Description     |                                                                                                                                           
|------------|-----------|-----------|----------------|
| `volatile`    | boolean    | No           |   If true, the function will recalculate each time    |
| `useGPU`  | boolean    | No            |   If true, the engine should use GPU to solve this function |

#### Parameters:

| Property     | Data type | Required | Description     |                                                                                                                                           
|------------|-----------|----------|----------------|
| `description` | string       |Yes           |    A description of the parameter  |
| `name` | string       | Yes           |    The name of the parameter.    |
| `optional` | boolean       | No           |   If true, the parameter is optional.                      |
| `repeating` | boolean       | No           |  If true, parameters will populate from a specified array. Note that functions all repeating parameters are considered optional parameters by definition.  |

### ID description

- Should be unique
- Uppercase
- only alphanumeric characters and periods

More: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming

## Use cases
With all this metadata and structure we can generate multiple developer experience tools:

### Editor helper
Better...
![Screenshot 2019-11-14 at 10 50 40](https://user-images.githubusercontent.com/4718998/68846118-cf587f80-06cc-11ea-832c-a795d3761de4.png)

or worse...
![Screenshot 2019-11-14 at 10 57 18](https://user-images.githubusercontent.com/4718998/68846551-910f9000-06cd-11ea-9c3b-a3cb4250d9a6.png)

### Help box modal
In all spreadsheet apps this is a responsive version of help pages listed below.
![Screenshot 2019-11-14 at 10 52 36](https://user-images.githubusercontent.com/4718998/68846209-fe6ef100-06cc-11ea-9233-dbc4748d4c47.png)

### Formula builder
With the list of `parameters` and their types we can generate form just like Excel does:
![Screenshot 2019-11-14 at 10 58 13](https://user-images.githubusercontent.com/4718998/68846634-ad133180-06cd-11ea-9a1d-ee8f3ddbc7dd.png)

#### Excel
![obraz](https://user-images.githubusercontent.com/4718998/68808917-10b84300-066b-11ea-842f-124d995c6154.png)
Source: https://support.office.com/en-us/article/average-function-047bac88-d466-426c-a32b-8f33eb960cf6

#### Google Spreadsheet
![obraz](https://user-images.githubusercontent.com/4718998/68807146-9639f400-0667-11ea-889c-d597a5d92088.png)
Source: https://support.google.com/docs/answer/3093139

#### Gnumeric
![obraz](https://user-images.githubusercontent.com/4718998/68806684-a1d8eb00-0666-11ea-8a69-9a5ac498c058.png)
Source: https://help.gnome.org/users/gnumeric/stable/gnumeric.html#gnumeric-function-SUM

**Comment by MartinDawson** [comment]
> Extracted from #36. We don't need metadata and helper translations inside the calculations engine. This is a translation format proposal for metadata described above. Both of them can be stored and published as a separate package/repository.
> 
> ### Meta definition
> ```ts
> const lang: LanguageDefinition = {
>   name: 'Polish',
>   code: 'pl-PL',
>   functions: {
>     'SUM': {
>       name: 'SUMA',
>       examples: ["=SUM(A1:A4)"],
>       description: "Short description for editor and category list.",
>       notes: "Longer article about formula and it's use cases. Might include Markdown for rich editing",
>       helpUrl: "",
>       parameters: [
>         {
>           name: "Parameter 1",
>           descriptions: "Short description for first parameter",
>         }
>       ],
>     },
>     'ADD': {
>       name: 'DODAJ',
>       // ...
>     },
>     // ... more functions
>   },
>   categories: {
>     'Financial': 'Finansowe',
>     'Statistical': 'Statystyczne',
>   }
> }
> ```

@wojciechczerniak If there is no imminent timeline for this then we will pick this up soon and implement all the meta for all the functions because formulas aren't really usable for users without detailed helpers for them. We only care about the English version so we would not be implementing any translations.

I'm confused why in your JSON example above the descriptions are in English but the code says Polish? Shouldn't the description and notes be in polish for this example?

Can you please also confirm your final thoughts for the implementation of this ticket?

A separate repository does not make sense to me. Instead it should be in hyperformula and just as a separate exported package that is tree-shakable so users who don't import it don't have to have the huge JS download size.

Perhaps using lerna as the monorepo package manager.

**Comment by MartinDawson** [comment]
@AMBudnik Sorry to tag you but I don't know who to tag anymore as wojciech isn't updating this repo anymore I think.

But please see my above comment (https://github.com/handsontable/hyperformula/issues/2#issuecomment-984634258) about wanting to pick this ticket up quite soon if handsontable doesn't have plans on doing it.

Also, could a hyperformula tag be created which notifies the relevant persons please?

For example handsontable has this: @handsontable to notify users. Would be good to get a @hyperformula tag with people in it that can give guidance on the issues for hyperformula that need doing.

**Comment by warpech** [comment]
> Can you please also confirm your final thoughts for the implementation of this ticket?

I am afraid that our final thoughts are to not do it as a part of HyperFormula. The reason is that whateve we could come up here, even with lots of work, would not necessarily satisfy all project's needs that want to make use of such metadata. For example, consider the descriptions of the formulas:

1. Descriptions are copyrightable so we need to write our own or settle the rights to get them from existing sources such as https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html. But the above source is technical and is not necessarily end-user friendly.
2. Descriptions are essentially part of the UX writing of the application, and any UX writer might have their own opinion about the writing style.
3. Descriptions must be presented in the application's UI language

For these reasons, it is possible that we will never actually get to implementing this issue.

> I'm surprised Handsontable doesn't have this functionality already as I'm not sure how users are even using the formulas well without it.

It is on Handsontable's list of nice-to-have features (https://github.com/handsontable/handsontable/discussions/8958, https://github.com/handsontable/handsontable/discussions/7944, also: https://github.com/handsontable/handsontable/issues/8508), but it is not that popular request. We will get to it at some point. But when we do it, it will make sense to actually implement that as part of the Handsontable application, not as part of Hyperformula - for the reasons given above.

@MartinDawson for a scope that is only narrowed down for your case, I think you could pull this off as a separate library.

----

I need to point out that the "translations" part of this issue is implemented:
- https://handsontable.github.io/hyperformula/guide/localizing-functions.html#localizing-custom-functions
- https://github.com/handsontable/hyperformula/tree/master/src/i18n/languages

**Comment by MartinDawson** [comment]
@warpech Makes sense. We will implement it in a seperate repo then on our side. Thanks

**Comment by warpech** [comment]
Thank you for understanding. I will close this issue to better indicate that this is our intention.
