### ISSUE TITLE
ISBLANK function bug

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#488]
`ISBLANK` results only to true if cell value is `null` and results to false if cell value is an empty string ""
this is not expected behaviour?

**Comment by bardek8** [comment]
According to the definitions of `ISBLANK` function we believe this is the expected behaviour. Or do we misunderstand it? 

We expect that this might be slightly inconvenient while exporting spreadsheet data to HyperFormula as one needs to ensure that empty cells become nulls and not empty strings.

Please let us know if you find an example in which HyperFormula handles blank cells incorrectly.

**Comment by doczoidberg** [comment]
@bardek8 
blank/null cell values can't be concenated.

https://github.com/handsontable/hyperformula/issues/495

**Comment by izulin** [comment]
to be closed?

**Comment by izulin** [comment]
I believe the behaviour of ISBLANK will be improved with PR #500 .

See https://github.com/handsontable/hyperformula/blob/pu/null-compatibility/test/null-compatibility.spec.ts#L38

**Comment by wojciechczerniak** [comment]
@doczoidberg Works as intended. We have to different values that are sent in JSON. `null` is a blank cell, empty string means that the cell was "touched" (copied&pasted, or editor was opened) and is no longer considered BLANK. Reference: https://docs.microsoft.com/en-us/office/troubleshoot/excel/isblank-function-return-false

Thanks for noticing and raising a discussion
