### ISSUE TITLE
Dependencies are not correctly collected

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#549]
### Description
Special functions (e.g. COLUMN) are designed to ignore its arguments as dependencies (so they do not need to be evaluated first), yet they have fallback that evaluates arguments.

```
    const engine = HyperFormula.buildFromArray([
      ['=SIN(1)'],
      ['=COLUMN(SUM(A1,A3))'],
      ['=SIN(1)'],
    ])
```

results in 

`Error: Value of the formula cell is not computed.`

### Steps to reproduce

1.
2.
3.

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Done in #550

**Comment by doczoidberg** [comment]
I get even more errors now:
```
Error: Value of the formula cell is not computed.
    at FormulaCellVertex.getCellValue (FormulaCellVertex.js:109)
    at AddressMapping.getCellValue (AddressMapping.js:120)
    at DependencyGraph.getCellValue (DependencyGraph.js:1245)
```

**Comment by izulin** [comment]
> I get even more errors now:
> 
> ```
> Error: Value of the formula cell is not computed.
>     at FormulaCellVertex.getCellValue (FormulaCellVertex.js:109)
>     at AddressMapping.getCellValue (AddressMapping.js:120)
>     at DependencyGraph.getCellValue (DependencyGraph.js:1245)
> ```

Should be addressed in the newest develop branch.

**Comment by doczoidberg** [comment]
the errors I had because of the new build are gone again now

**Comment by doczoidberg** [comment]
would be nice to get the cell where the error happens

**Comment by bardek8** [comment]
We return the address of the cell where the error originated (see the #529). However, in your case of `Error: Value of the formula cell is not computed.` this was an exception which we do not wrap into more meaningful comments. A rule of the thumb would be that exceptions are due to an internal error that probably should be reported as an issue for further investigation.

On the positive side, we hope that error comments will be sufficiently meaningful :)
