### ISSUE TITLE
Brief summary of differences between HyperFormula and Google Sheets and Excel

### ISSUE THREAD

**Issue by bardek8** [handsontable/hyperformula#603]
### General differences in the behavior

HyperFormula behaves slightly differently than Google Sheets or Excel. The inconsistencies are due to the current limitations of HyperFormula and/or inconsistency between Excel and Google Sheets.
In most cases the differences should not be observed by the user, but we list them here for the completeness:

[Differences between HyperFormula and Excel + Google Sheets.xlsx](https://github.com/handsontable/hyperformula/files/5935113/Differences.between.HyperFormula.and.Excel.%2B.Google.Sheets.xlsx)

### Differences in the built-in functions

There are also some tiny differences in the exact implementation of the built-in functions of HyperFormula, which mostly arise while handling corner cases and boundary values passed to the functions. They are all covered in the unit tests, but below we list them all in one place:

[Differences in the implementation of the built-in functions.xlsx](https://github.com/handsontable/hyperformula/files/5935148/Differences.in.the.implementation.of.the.built-in.functions.xlsx)

**Comment by krzysztofspilka** [comment]
Thanks @bardek8! It might be more handy to convert them to markdown, which I've done below.

File: Differences between HyperFormula and Excel + Google Sheets.xlsx

| Functionality | Example | HyperFormula | Google Sheets | Excel |
|-|-|-|-|-|
| Dependency collection | A1:=IF(FALSE(),A1,0) ISREF(A1) | Dependencies are collected during the parsing phase which finds cycles that wouldn’t   appear in the evaluation. CYCLE error for both the examples. | Dependencies are collected during evaluation. Returns 0 for both the examples. | Same as in GoogleSheets. |
| Named expressions and named ranges | SALARY:=$A$10       COST:=10*$B$5+100       PROFIT:=SALARY-COST       A1:=SALARY-COST | Named expressions can be used to create aliases for simple values or formulas, but we allow only absolute addresses (e.g SALARY:= $A$10). Named expressions can be global or scoped to one sheet only. They can contain other named expressions. | Named expressions are not available. Named ranges can be used to create aliases for addresses and ranges. | Named ranges and scoped named expressions are available. |
| Applying a range to a function taking a single value | ABS(A1:B3) | “WrongType” error. | If there is exactly one cell from the range in the same row/column as the formula, returns its value. Otherwise throws “An array value could not be found.” error. | Fills a number of cells, with the formula in the top-left corner. |
| Applying operator to a range | A1:A3% A1:A3 + 10 | “ScalarExpected” error. | Same as above. | Same as above. |
| Applying scalar value to a function taking range | COLUMNS(A1) | “CellRangeExpected” error. | Treats the element as length-1 range. Returns 1 for the example. | Same as in Google Sheets. |
| Different coercion of explicit arguments | VARP(2, 3, 4, TRUE(), FALSE(), "1",) | 1.9592, based on the behavior of Excel. | GoogleSheets implementation is not consistent with the standard (see also VAR.S, STDEV.P and STDEV.S function.) | 1,9592 |
| Ranges created with “:” operator | A1:A2, A$1:$A$2       A:C, 1:2 Sheet1!A1:A2 | Allowed ranges consist of two addresses (A1:B5), columns (A:C) or rows (3:5). They   cannot be mixed nor contain a named expression. | Everything allowed. | Same as in Google Sheets. |
| Formatting using TEXT function | TEXT(A1,"dd-mm-yy") TEXT(A1,"###.###”) | Not all options of formatting are supported. E.g. only a subset of tokens for   formatting dates is supported (‘hh’, ‘mm’, ‘ss’, ‘am’, ‘pm’, ‘a’, ‘p’, ‘dd’,   ‘yy’ and ‘yyyy’) and we cannot format a currency in TEXT function. | A wide variety of options for string formatting is supported. | Same as in Google Sheets. |

----

There  are also some small incompatibilities with the implementation of builtin-functions compared to Excel or Google Sheets, mainly due to different handling of corner cases or input coercion.

**Comment by krzysztofspilka** [comment]
File: Differences in the implementation of the built-in functions.xlsx

| Function | Example | HyperFormula | GoogleSheets | Excel | Comment |
|-|-|-:|-:|-:|-|
| TBILLEQ | =TBILLEQ(0, 180, 1.9) | 38,5278 | NUM | NUM |  |
| TBILLEQ | =TBILLEQ(0, 180, 2) | 0,0000 | NUM | 0,0000 |  |
| TBILLEQ | =TBILLEQ("1/2/2000",   "31/1/2001", 0.1) | 0,1128 | VALUE | VALUE |  |
| TBILLEQ | =TBILLEQ(0, 360, 0.1) | 0,1127 | 0,1097 | 0,1097 | We are implementing   exactly what is in the documentation of Excel. Apparently Google Sheets and   Excel use a different logic. |
| TBILLEQ | =TBILLEQ(0, 365, 0.1) | 0,1128 | 0,1098 | 0,1098 |  |
| GCD | =GCD(1000000000000000000.0) | NUM | 1E+18 | NUM |  |
| COMBIN | =COMBIN(1030, 0) | NUM | NUM | 1,0000 |  |
| RRI | =RRI(1, -1, -1) | 0,0000 | NUM | 0,0000 |  |
| DAYS | =DAYS(-1, 0) | NUM | -1,0000 | NUM |  |
| DAYS | =DAYS(0, -1) | NUM | 1,0000 | NUM |  |
| DATEDIF | =DATEDIF(-1, 0,   "Y") | NUM | 0,0000 | NUM |  |
| RATE | =RATE(12, -100, 400, 100, 1) | -0,4997 | 0,3100 | -0,4997 | Google Sheets returns an   incorrect result. We followed the definition from documentation of Excel   (this function requires solving equation via newton method, which is   error-prone) |
| RATE | =RATE(12, -100, 400, 1, 1) | -0,9901 | 0,3200 | -0,9901 |  |
| RATE | =RATE(12, -100, 400, 0, 1) | NUM | 0,3200 | NUM |  |
| RATE | =RATE(12, -100, 400, -100, 1) | NUM | 0,3200 | NUM |  |
| RATE | =RATE(0.9, -100, 400) | -0,7962 | NUM | -0,7962 |  |
| LCMP | =LCM(1000000,1000001,1000002,1000003) | NUM | 5,00003E+23 | NUM |  |
| TBILLPRICE | =TBILLPRICE(0, 180, 1.9) | 5,0000 | NUM | 5,0000 |  |
| TBILLPRICE | =TBILLPRICE(0, 180, 2) | 0,0000 | NUM | 0,0000 |  |
| NPV | =NPV(1, TRUE(), 1) | 0,7500 | 0,5000 | 0,7500 | We immediately   instantiate references to single cells to their values instead of treating   them as 1-length ranges, which slightly changes behavior of some functions   (e.g. NPV). |
| NPV | =NPV(1,B1) where B1 = true | 0,5000 | 0,0000 | 0,0000 |  |
| POISSON.DIST | =POISSON.DIST(-0.01, 0, FALSE()) | NUM | 1,0000 | NUM |  |
| POISSON.DIST | =POISSON.DIST(0, -0.01, FALSE()) | NUM | NUM | 1,0101 |  |
| DB | =DB(1000000,100000,6,7,7) | 15845,1000 | NUM | 15845,0985 |  |
| BETA.DIST | =BETA.DIST(1, 2, 3) | N/A | 1,0000 | NUM |  |
| BETA.DIST | =BETA.DIST(0, 1, 1, FALSE()) | NUM | 0,0000 | NUM |  |
| BETA.DIST | =BETA.DIST(0.6, 1, 1, FALSE(),   0.6, 0.7) | NUM | 0,0000 | 0,0000 |  |
| BETA.DIST | =BETA.DIST(0.7, 1, 1, FALSE(),   0.6, 0.7) | NUM | 0,0000 | 0,0000 |  |
| GAMMA | =GAMMA(-2.5) | -0,9453 | NUM | -0,9453 |  |
| BINOM.DIST | =BINOM.DIST(0.5, 0.4, 1,   FALSE()) | N/A | NUM | 1,0000 |  |
| NEGBINOM.DIST | =NEGBINOM.DIST(0, 1, 0, FALSE()) | 0,0000 | N/A | NUM |  |
| NEGBINOM.DIST | =NEGBINOM.DIST(0, 1, 1, FALSE()) | 1,0000 | N/A | NUM |  |
| T.INV | =T.INV(0, 1) | NUM | NUM | DIV/0 | Excel and Google Sheets return  different errors |
| BETA.INV | =BETA.INV(1, 1, 1) | 1,0000 | 1,0000 | NUM |  |
| WEIBULL.DIST | =WEIBULL.DIST(0, 1, 1, FALSE()) | 1,0000 | 1,0000 | 0,0000 | There is 0^0 in the formula,   which is undefined and differently handled by Excel and Google Sheets. |
| HYPGEOM.DIST | =HYPGEOM.DIST(12.1, 12, 20, 40,   TRUE()) | NUM | N/A | 1,0000 |  |
| HYPGEOM.DIST | =HYPGEOM.DIST(12.1, 20, 12, 40,   TRUE()) | NUM | N/A | 1,0000 |  |
| HYPGEOM.DIST | =HYPGEOM.DIST(1, 2, 3, 4) | N/A | 0,5000 | NUM | The function in Google Sheets   accepts 4 instead of 5 arguments |
| HYPGEOM.DIST | =HYPGEOM.DIST(4, 12, 20, 40,   TRUE()) | 0,1504 | N/A | 0,1504 | The function in Google Sheets   accepts 4 instead of 5 arguments |
| TDIST | =TDIST(0, 1, 1.5) | NUM | 0,5000 | 0,5000 |  |
| T.INV.2T | =T.INV.2T(0, 1) | NUM | NUM | DIV/0 | Excel and Google Sheets return   different errrors |
| T.DIST | =T.DIST(1, 0.9, FALSE()) | NUM | NUM | DIV/0 | Excel and Google Sheets return   different errrors |
| AVEDEV | =AVEDEV(TRUE(),FALSE(),) | 0,4444 | 0,0000 | 0,4444 | Different coercion of   the input |
| LARGE | =LARGE(TRUE(),1) | NUM | NUM | 1,0000 |  |
| COUNTA | =COUNTA(1,) | 2,0000 | 1,0000 | 2,0000 | Different handling empty   arguments |
| XNPV | =XNPV(-0.9, A2:D2, A3:D3) where   2nd and 3rd row: 1,2,3,4 | 10,1272 | 10,12716959 | NUM | Excel implements only Rate>0   (even though it states in the documentation that Rate>-1) |
| SKEW | =SKEW(TRUE(),FALSE(),) | 1,7321 | DIV/0 | 1,7321 | Different coercion of   the input |
| HARMEAN | =HARMEAN(TRUE(),"4") | 1,6000 | 4,0000 | 1,6000 | Different coercion of   the input |
| GEOMEAN | =GEOMEAN(TRUE(),"4") | 2,0000 | 4,0000 | 2,0000 | Different coercion of   the input |
| CHISQ.TEST | =CHISQ.TEST(A1:C2, A1:F1) | N/A | N/A | DIV/0 | Excel and Google Sheets return   different errrors |
| BINOM.INV | =BINOM.INV(1, 0.8, 0.2) | 0,0000 | 1,0000 | 1,0000 |  |
| BINOM.INV | =BINOM.INV(-0.001, 0.5, 0.5) | NUM | 0,0000 | NUM |  |
| BINOM.INV | =BINOM.INV(10, 0, 0.5) | 0,0000 | NUM | NUM |  |
| BINOM.INV | =BINOM.INV(10, 1, 0.5) | 10,0000 | NUM | NUM |  |
| DEVSQ | =DEVSQ(A2,A3) | 0,0000 | 0,0000 | NUM |  |

**Comment by MartinDawson** [comment]
I raised this issue here: https://github.com/handsontable/hyperformula/issues/692

But here's the difference for NORMSDIST:


Function | Example | HyperFormula | GoogleSheets | Excel | Comment
NORMSDIST | =NORMSDIST(0, TRUE()) | 0.5 | Wrong number of args | Wrong number of args | --



I do think this should go in as an alias in Hyperformula though.

NORM.S.DIST is a different function that matches hyperformula.
