### ISSUE TITLE
NORMSDIST not working

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#692]
### Description

Produces object object.

I tried the same in google sheets and it correctly calculates the value.

In your code it says the params are:

Number, Boolean.

So I also tried: =NORMSDIST(1, TRUE).

Same result.

### Steps to reproduce

1. =NORMSDIST(1)

### Demo

See here: https://codesandbox.io/s/charming-lederberg-cci4b?file=/src/data.js

### Your environment

* HyperFormula version: Demo
* Browser Name and version: Chrome latest
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Do you have `TRUE` defined as named expression? Otherwise, `TRUE()` is a function

If you stringify the `[object Object]` correctly both use cases will return a message saying what's wrong:

`=NORMSDIST(1)` ==> `{"value":"#N/A","address":"main!D1","type":"NA","message":"Wrong number of arguments."}`
`=NORMSDIST(1, TRUE)` ==> `{"value":"#NAME?","address":"main!D1","type":"NAME","message":"Named expression TRUE not recognized."}`
`=NORMSDIST(1, TRUE())` ==> "0.84"

**Comment by izulin** [comment]
I believe we implemented excel version of this function, which does not define default values for its arguments (and hence requires all 4 arguments).

**Comment by MartinDawson** [comment]
@wojciechczerniak Thanks. I saw that second error but didn't understand it as I thought TRUE was enabled by default.

**Comment by MartinDawson** [comment]
@izulin Ah okay, thanks for clarifying!
