### ISSUE TITLE
A bug with precisionRounding option changes numbers in cells

### ISSUE THREAD

**Issue by YuriKirilin** [handsontable/hyperformula#856]
### Description

The configuration option precisionRounding must affect only digits after the decimal point.  In fact, it affects/changes the whole number.

### Steps to reproduce
1. Save the following code as a disk file
2. Run the file from a browser
```<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Precision Bug Demo</title>
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/hyperformula/dist/hyperformula.full.min.js"></script>
<div id="out"></div>
<script>
(function() {
	const options = {
		precisionRounding: 4,
		licenseKey: 'gpl-v3'
	};
	sheetData = JSON.parse('{"P":[[100005]]}');
	const hfInstance = HyperFormula.buildFromSheets(sheetData, options);
	const A1Value = hfInstance.getCellValue({ sheet: 0, col: 0, row: 0 });
	document.getElementById('out').innerText = 'Wrong out value: 100005 !=' + A1Value; // Wrong out value: 100005 !=100010
})();
</script>
</body>
</html>
```
Although the initial input cell value is 100005, the output cell value is 100010.
Removing precisionRounding out of options, fixes the problem.

### Your environment

* HyperFormula version: 1.3.0
* Browser Name and version: Firfox 94.0.1
* Operating System: MS Windows

**Comment by wojciechczerniak** [comment]
Hi @YuriKirilin, thank you for reporting. We will investigate this issue

**Comment by bardek8** [comment]
@YuriKirilin, thank you for pointing this out! 
Actually you found a bug in our documentation: `precisionRounding` parameter denotes the number of significant digits we consider, not the number of digits after decimal point. We'll provide a fix to docs soon.

Then, in the example you provided the behavior is correct: you round the value of the cell to 4 most significant digits, so 100005 becomes 10010.

**Comment by AMBudnik** [comment]
Hi @YuriKirilin 

Sorry for such a delay in getting back to you. We made the necessary changes in the documentation with https://github.com/handsontable/hyperformula/pull/868 so this topic can be closed as solved.
Thank you again for your effort to report an issue.

**Comment by Dhatchanamoorthi8** [comment]
### Formula evaluation auto-rounds numbers (expected "52.50000", got "52.5")

Hi HyperFormula team 👋,

I'm using HyperFormula.buildFromSheets() to evaluate some sheet data, and I noticed an issue with how numeric results are returned after formula evaluation.

My input (handsontableJson) looks like this:
`{
  "Sheet2": [
    [ "52.50000", "=ROUND(AVERAGE(A1:A5),5)" ],
    [ "52.50000", "" ],
    [ "52.50000", "" ],
    [ "52.50000", "" ],
    [ "52.50000", "" ]
  ]
}
`
`const hfInstance = HyperFormula.buildFromSheets(handsontableJson, {
  licenseKey: 'gpl-v3',
  smartRounding: false,
});
const sheetId = hfInstance.getSheetId(sheetKey);
const evaluatedData = hfInstance.getSheetValues(sheetId);
console.log(evaluatedData);
`
`[
  [ 52.5, 52.5 ],
  [ 52.5, "" ],
  [ 52.5, "" ],
  [ 52.5, "" ],
  [ 52.5, "" ]
]
`
**Problem:**

- I expected the result to be "52.50000", preserving the 5 decimal places, because the original formula uses =ROUND(AVERAGE(A1:A5),5).
- 
- But HyperFormula returns it as 52.5, losing the trailing zeros.

**Context:**

- smartRounding: false is already set.
- 
- I would like to retain the precision as formatted (5 decimal places), especially for PDF generation use cases where the exact number format matters.

**Question:**

- Is there a built-in way to preserve the decimal formatting (e.g., "52.50000" instead of "52.5")?
- 
- If not, could this be considered as an enhancement, or is there a recommended workaround?

Thanks a lot for your amazing work on HyperFormula! 🚀
